export const FETCHING_DATA = "FETCHING_DATA";
export const FETCHING_DATA_SUCCESS = "FETCHING_DATA_SUCCESS";
export const FETCHING_DATA_FAILURE = "FETCHING_DATA_FAILURE";
export const FIND_PRODUCTS = "FIND_PRODUCTS";
export const ADD_TO_CART_ACTION = "ADD_TO_CART_ACTION";
export const ADD_TO_CART_ACTION_HIDE = "ADD_TO_CART_ACTION_HIDE";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const QTY_UP = "QTY_UP";
export const QTY_DOWN = "QTY_DOWN";
export const CHECKOUT_REQUEST = "CHECKOUT_REQUEST";
export const CHECKOUT_FAILURE = "CHECKOUT_FAILURE";
export const GET_ORDER_ITEMS = "GET_ORDER_ITEMS";
export const GET_ORDER_ADDRESS = "GET_ORDER_ADDRESS";
export const GET_ORDER_PAYMENT = "GET_ORDER_PAYMENT";

// Authentification
export const EMAIL_CHANGED = "EMAIL_CHANGED";
export const PASSWORD_CHANGED = "PASSWORD_CHANGED";
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const REGISTER_USER = "REGISTER_USER";
export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const LOGOUT_USER = "LOGOUT_USER";

// Profile Data
export const USER_REQUEST_ERROR = "USER_REQUEST_ERROR";
export const UPDATE_USER_DATA = "UPDATE_USER_DATA";
export const UPDATE_USER_DATA_SUCCESS = "UPDATE_USER_DATA_SUCCESS";
export const ADD_NEW_ADDRESS = "ADD_NEW_ADDRESS";
export const ADD_NEW_ADDRESS_SUCCESS = "ADD_NEW_ADDRESS_SUCCESS";
export const UPDATE_ADDRESS = "UPDATE_ADDRESS";
export const UPDATE_ADDRESS_SUCCESS = "UPDATE_ADDRESS_SUCCESS";
export const DELETE_ADDRESS = "DELETE_ADDRESS";
export const DELETE_ADDRESS_SUCCESS = "DELETE_ADDRESS_SUCCESS";
export const ADD_NEW_ORDER = "ADD_NEW_ORDER";
export const ADD_NEW_ORDER_SUCCESS = "ADD_NEW_ORDER_SUCCESS";
